theme: jekyll-theme-slate

title: Levi Starrett
description: Software Engineer

phone: +1 (765) 532-4829
email: levi@roxsoftware.com
resume-link: https://leviathan747.github.io/resume/
github-link: https://github.com/leviathan747/
linkedin-link: http://www.linkedin.com/in/levistarrett/
