theme: jekyll-theme-slate

title: Levi Starrett
description: Software Engineer

email: levi@roxsoftware.com
phone: +1 (765) 532-4829
resume-link: https://leviathan747.github.io/resume/
github-link: https://github.com/leviathan747/
linkedin-link: https://www.linkedin.com/in/levistarrett/
